from .loss_interface import LossInterface
from .loss_interface import calculate_fitness
from .AestheticLoss import AestheticLoss
from .Aesthetic2Loss import Aesthetic2Loss
from .ClipPrompt import ClipPrompt
from .InputImage import InputImage
from .GaussianLoss import GaussianLoss
from .PaletteLoss import PaletteLoss
from .ResmemLoss import ResmemLoss
from .SaturationLoss import SaturationLoss
from .SmoothnessLoss import SmoothnessLoss
from .SymmetryLoss import SymmetryLoss
from .StyleFitness import StyleLoss
from .EdgeLoss import EdgeLoss
