from .fitness_interface import FitnessInterface
from .fitness_interface import calculate_fitness
from .AestheticFitness import AestheticFitness
from .Aesthetic2Fitness import Aesthetic2Fitness
from .ClipPrompt import ClipPrompt
from .InputImage import InputImage
from .GaussianLoss import GaussianLoss
from .PaletteLoss import PaletteLoss
from .ResmemFitness import ResmemFitness
from .SaturationFitness import SaturationFitness
from .SmoothnessFitness import SmoothnessFitness
from .SymmetryLoss import SymmetryFitness
from .StyleLoss import StyleLoss
from .EdgeLoss import EdgeFitness
